kits:
  - name: <a1>Armorer
    description: When the game starts, receive the following items:\n  - Wooden Sword\n  - Iron Chestplate\n  - Iron Leggings
    icon: minecraft:iron_chestplate
    items:
      0:
        material: minecraft:wooden_sword
      chestplate:
        material: minecraft:iron_chestplate
      leggings:
        material: minecraft:iron_leggings
  - name: <a1>Swordsman
    description: When the game starts, receive the following items:\n  - Diamond Sword\n  - Leather Tunic\n  - Leather Pants
    icon: minecraft:diamond_sword
    items:
      0:
        material: minecraft:diamond_sword
      chestplate:
        material: minecraft:leather_chestplate
      leggings:
        material: minecraft:leather_leggings
  - name: <a1>Builder
    description: When the game starts, receive the following items:\n  - Wooden Sword\n  - 48 Wool\n  - Leather Tunic\n  - Leather Pants
    icon: minecraft:white_wool
    items:
      0:
        material: minecraft:wooden_sword
      1:
        material: minecraft:white_wool
        amount: 48
      chestplate:
        material: minecraft:leather_chestplate
      leggings:
        material: minecraft:leather_leggings
  - name: <a1>Trader
    description: When the game starts, receive the following items:\n  - Wooden Sword\n  - 32 Iron\n  - Leather Tunic\n  - Leather Pants
    icon: minecraft:iron_ingot
    items:
      0:
        material: minecraft:wooden_sword
      1:
        material: minecraft:iron_ingot
        amount: 32
      chestplate:
        material: minecraft:leather_chestplate
      leggings:
        material: minecraft:leather_leggings
generators:
  spawn:
    - item:
        material: minecraft:iron_ingot
      cooldown: 1
      amount: 1
    - item:
        material: minecraft:gold_ingot
      cooldown: 3
      amount: 1
  diamond:
    - item:
        material: minecraft:diamond
      cooldown: 25
      amount: 1
  emerald:
    - item:
        material: minecraft:emerald
      cooldown: 35
      amount: 1
shop:
  - row: 1
    column: 1
    material: minecraft:white_wool
    amount: 16
    price: 10
    currency: minecraft:iron_ingot
  - row: 1
    column: 2
    material: minecraft:oak_wood
    amount: 8
    price: 10
    currency: minecraft:gold_ingot
  - row: 1
    column: 3
    material: minecraft:end_stone
    amount: 8
    price: 50
    currency: minecraft:iron_ingot
  - row: 2
    column: 1
    material: minecraft:shears
    amount: 1
    price: 50
    currency: minecraft:iron_ingot
  - row: 2
    column: 2
    material: minecraft:stone_pickaxe
    amount: 1
    price: 50
    currency: minecraft:iron_ingot
  - row: 2
    column: 3
    material: minecraft:stone_axe
    amount: 1
    price: 50
    currency: minecraft:iron_ingot
  - row: 2
    column: 4
    material: minecraft:iron_pickaxe
    amount: 1
    price: 20
    currency: minecraft:gold_ingot
  - row: 2
    column: 5
    material: minecraft:iron_axe
    amount: 1
    price: 20
    currency: minecraft:gold_ingot
  - row: 3
    column: 1
    material: minecraft:stone_sword
    amount: 1
    price: 15
    currency: minecraft:iron_ingot
  - row: 3
    column: 2
    material: minecraft:iron_sword
    amount: 1
    price: 10
    currency: minecraft:gold_ingot
  - row: 3
    column: 3
    material: minecraft:diamond_sword
    amount: 1
    price: 5
    currency: minecraft:emerald
  - row: 3
    column: 4
    item:
      material: minecraft:stick
      enchants:
        minecraft:knockback: 3
      lore:
        - <gray>Use this to wack your enemies
        - <gray>off the map!
    price: 3
    currency: minecraft:emerald
  - row: 4
    column: 1
    material: minecraft:iron_helmet
    amount: 1
    price: 20
    currency: minecraft:gold_ingot
  - row: 4
    column: 2
    material: minecraft:iron_chestplate
    amount: 1
    price: 5
    currency: minecraft:emerald
  - row: 4
    column: 3
    material: minecraft:iron_leggings
    amount: 1
    price: 5
    currency: minecraft:emerald
  - row: 4
    column: 4
    material: minecraft:iron_boots
    amount: 1
    price: 20
    currency: minecraft:gold_ingot
  - row: 5
    column: 1
    material: minecraft:fire_charge
    amount: 1
    price: 50
    currency: minecraft:iron_ingot
  - row: 5
    column: 2
    material: minecraft:bow
    amount: 1
    price: 20
    currency: minecraft:gold_ingot
  - row: 5
    column: 2
    item:
      material: minecraft:bow
      enchants:
        minecraft:punch: 1
    amount: 1
    price: 6
    currency: minecraft:emerald
  - row: 5
    column: 3
    material: minecraft:arrow
    amount: 8
    price: 20
    currency: minecraft:iron_ingot
  - row: 5
    column: 4
    material: minecraft:egg
    amount: 16
    price: 20
    currency: minecraft:iron_ingot