categories:
  - id: global
    name: Global
    material: minecraft:diamond_block
    groups:
      - id: firework_color
        name: <lang:cosmetic.global.fw_color>
        material: minecraft:firework_rocket
        description: <lang:cosmetic.global.fw_color.desc>
        cosmetics:
          - id: global_firework_red
            name: <lang:color.minecraft.red>
            material: minecraft:red_wool
            description: <lang:cosmetic.global.fw_color.all.desc:'<lang:color.minecraft.red>'>
            cost: 500
          - id: global_firework_orange
            name: <lang:color.minecraft.orange>
            material: minecraft:orange_wool
            description: <lang:cosmetic.global.fw_color.all.desc:'<lang:color.minecraft.orange>'>
            cost: 500
          - id: global_firework_yellow
            name: <lang:color.minecraft.yellow>
            material: minecraft:yellow_wool
            description: <lang:cosmetic.global.fw_color.all.desc:'<lang:color.minecraft.yellow>'>
            cost: 500
          - id: global_firework_green
            name: <lang:color.minecraft.green>
            material: minecraft:green_wool
            description: <lang:cosmetic.global.fw_color.all.desc:'<lang:color.minecraft.green>'>
            cost: 500
          - id: global_firework_blue
            name: <lang:color.minecraft.blue>
            material: minecraft:blue_wool
            description: <lang:cosmetic.global.fw_color.all.desc:'<lang:color.minecraft.blue>'>
            cost: 500
          - id: global_firework_purple
            name: <lang:color.minecraft.purple>
            material: minecraft:purple_wool
            description: <lang:cosmetic.global.fw_color.all.desc:'<lang:color.minecraft.purple>'>
            cost: 500
          - id: global_firework_rainbow
            name: <lang:cosmetic.global.fw_color.rainbow>
            material: minecraft:emerald_block
            description: <lang:cosmetic.global.fw_color.all.desc:'<lang:cosmetic.global.fw_color.rainbow>'>
            cost: 2000
  - name: Lobby
    material: minecraft:dragon_head
    groups:
      - id: double_jump_effect
        name: <lang:cosmetic.lobby.doublejump>
        material: minecraft:iron_boots
        description: <lang:cosmetic.lobby.doublejump.desc>
        cosmetics:
          - id: lobby_double_jump_note
            name: <lang:block.minecraft.note_block>
            material: minecraft:note_block
            description: <lang:cosmetic.lobby.doublejump.note.desc>
            cost: 1500
          - id: lobby_double_jump_cloud
            name: Cloud
            material: minecraft:white_wool
            description: <lang:cosmetic.lobby.doublejump.cloud.desc>
            cost: 1500
      - id: hat
        name: <lang:cosmetic.lobby.hat>
        material: minecraft:player_head
        description: <lang:cosmetic.lobby.hat.desc>
        cosmetics:
          - id: lobby_hat_glass
            name: <lang:cosmetic.lobby.hat.glass>
            material: minecraft:glass
            description: <lang:cosmetic.lobby.hat.glass.desc>
            cost: 500
          - id: lobby_hat_ice
            name: <lang:block.minecraft.ice>
            material: minecraft:ice
            description: <lang:cosmetic.lobby.hat.ice.desc>
            cost: 500
          - id: lobby_hat_slime
            name: <lang:entity.minecraft.slime>
            material: minecraft:slime_block
            description: <lang:cosmetic.lobby.hat.slime.desc>
            cost: 500
          - id: lobby_hat_honey
            name: <lang:cosmetic.lobby.hat.honey>
            material: minecraft:honey_block
            description: <lang:cosmetic.lobby.hat.honey.desc>
            cost: 500
          - id: lobby_hat_jack_o_lantern
            name: <lang:block.minecraft.jack_o_lantern>
            material: minecraft:jack_o_lantern
            description: <lang:cosmetic.lobby.hat.jack_o_lantern.desc>
            cost: 500
          - id: lobby_hat_compass
            name: <lang:item.minecraft.compass>
            material: minecraft:compass
            description: <lang:cosmetic.lobby.hat.compass.desc>
            cost: 500
          - id: lobby_hat_clock
            name: <lang:item.minecraft.clock>
            material: minecraft:clock
            description: <lang:cosmetic.lobby.hat.clock.desc>
            cost: 500
          - id: lobby_hat_netherite_helmet
            name: <lang:cosmetic.lobby.hat.netherite>
            material: minecraft:netherite_helmet
            description: <lang:cosmetic.lobby.hat.netherite.desc>
            cost: 500
          - id: lobby_hat_creeper_head
            name: <lang:block.minecraft.creeper_head>
            material: minecraft:creeper_head
            description: <lang:cosmetic.lobby.hat.creeper.desc>
            cost: 500
          - id: lobby_hat_zombie_head
            name: <lang:block.minecraft.zombie_head>
            material: minecraft:zombie_head
            description: <lang:cosmetic.lobby.hat.zombie.desc>
            cost: 500
          - id: lobby_hat_steve_head
            name: <lang:cosmetic.lobby.hat.steve>
            material: minecraft:player_head
            description: <lang:cosmetic.lobby.hat.steve.desc>
            cost: 500
          - id: lobby_hat_skeleton_skull
            name: <lang:block.minecraft.skeleton_skull>
            material: minecraft:skeleton_skull
            description: <lang:cosmetic.lobby.hat.skeleton.desc>
            cost: 500
          - id: lobby_hat_wither_skeleton_skull
            name: <lang:block.minecraft.wither_skeleton_skull>
            material: minecraft:wither_skeleton_skull
            description: <lang:cosmetic.lobby.hat.wither_skeleton.desc>
            cost: 500
          - id: lobby_hat_dragon_head
            name: <lang:block.minecraft.dragon_head>
            material: minecraft:dragon_head
            description: <lang:cosmetic.lobby.hat.dragon.desc>
            cost: 5000
          - id: lobby_hat_rainbow
            name: <lang:cosmetic.lobby.hat.rainbow>
            material: minecraft:blue_stained_glass
            description: <lang:cosmetic.lobby.hat.rainbow.desc>
            cost: 7500
  - id: wackymaze
    name: WackyMaze
    material: minecraft:stick
    groups:
      - name: <lang:cosmetic.wackymaze.kbstick>
        material: minecraft:stick
        description: <lang:cosmetic.wackymaze.kbstick.desc>
        cosmetics:
          - id: wackymaze_stick_fish
            name: <lang:cosmetic.wackymaze.kbstick.fish>
            material: minecraft:cod
            description: <lang:cosmetic.wackymaze.kbstick.fish.desc>
            cost: 5000
          - id: wackymaze_stick_door
            name: <lang:cosmetic.wackymaze.kbstick.door>
            material: minecraft:oak_door
            description: <lang:cosmetic.wackymaze.kbstick.door.desc>
            cost: 5000
          - id: wackymaze_stick_bamboo
            name: <lang:cosmetic.wackymaze.kbstick.bamboo>
            material: minecraft:bamboo
            description: <lang:cosmetic.wackymaze.kbstick.bamboo.desc>
            cost: 5000
          - id: wackymaze_stick_hoe
            name: <lang:cosmetic.wackymaze.kbstick.hoe>
            material: minecraft:netherite_hoe
            description: <lang:cosmetic.wackymaze.kbstick.hoe.desc>
            cost: 5000
          - id: wackymaze_stick_deadbush
            name: <lang:cosmetic.wackymaze.kbstick.deadbush>
            material: minecraft:dead_bush
            description: <lang:cosmetic.wackymaze.kbstick.deadbush.desc>
            cost: 5000
  - id: fastfall
    name: FastFall
    material: minecraft:iron_boots
    groups:
      - id: boots
        name: <lang:cosmetic.fastfall.boots>
        material: minecraft:leather_boots
        description: <lang:cosmetic.fastfall.boots.desc>
        cosmetics:
          - id: fastfall_boots_standard
            name: <lang:cosmetic.fastfall.boots.leather>
            material: minecraft:leather_boots
            description: <lang:cosmetic.fastfall.boots.leather.desc>
            cost: 250
          - id: fastfall_boots_netherite
            name: <lang:cosmetic.fastfall.boots.netherite>
            material: minecraft:netherite_boots
            description: <lang:cosmetic.fastfall.boots.netherite.desc>
            cost: 1000
          - id: fastfall_boots_gold
            name: <lang:cosmetic.fastfall.boots.gold>
            material: minecraft:golden_boots
            description: <lang:cosmetic.fastfall.boots.gold.desc>
            cost: 15000
          - id: fastfall_boots_tnt
            name: <lang:cosmetic.fastfall.boots.tnt>
            item:
              material: minecraft:leather_boots
              dye: 255, 0, 0
            description: <lang:cosmetic.fastfall.boots.tnt.desc>
            cost: 15000
  - id: infinijump
    name: Infinijump
    material: minecraft:feather
    groups:
      - id: blocks
        name: <lang:cosmetic.infinijump.block_sets>
        material: minecraft:grass_block
        description: <lang:cosmetic.infinijump.block_sets.desc>
        cosmetics:
          - id: infinijump_blocks_red
            name: <lang:cosmetic.infinijump.blocks.red>
            material: minecraft:red_concrete
            cost: 250
          - id: infinijump_blocks_green
            name: <lang:cosmetic.infinijump.blocks.green>
            material: minecraft:green_concrete
            cost: 250
          - id: infinijump_blocks_blue
            name: <lang:cosmetic.infinijump.blocks.blue>
            material: minecraft:blue_concrete
            cost: 250
          - id: infinijump_blocks_rainbow_concrete
            name: <lang:cosmetic.infinijump.blocks.rainbow_concrete>
            description: <lang:cosmetic.infinijump.blocks.rainbow_concrete.desc>
            material: minecraft:cyan_concrete
            cost: 2500
          - id: infinijump_blocks_rainbow_wool
            name: <lang:cosmetic.infinijump.blocks.rainbow_wool>
            description: <lang:cosmetic.infinijump.blocks.rainbow_wool.desc>
            material: minecraft:cyan_wool
            cost: 2500
          - id: infinijump_blocks_jungle
            name: <lang:cosmetic.infinijump.blocks.jungle>
            description: <lang:cosmetic.infinijump.blocks.jungle.desc>
            material: minecraft:flowering_azalea_leaves
            cost: 2500