categories:
  - name: FastFall
    material: minecraft:iron_boots
    groups:
      - name: Boots (Decorative)
        material: minecraft:leather_boots
        description: |
          Boots for your feet! They
          must be uncomfortable after
          falling so many times...
          
          * All FastFall cosmetics
          are decorative and have 
          no impact on gameplay.
        cosmetics:
          - id: fastfall_boots_standard
            name: Standard
            material: minecraft:leather_boots
            description: "Can't get more simple than this."
            cost: 250
          - id: fastfall_boots_netherite
            name: Netherite
            material: minecraft:netherite_boots
            description: "You know they don't protect against fall damage, right?"
            cost: 1000
          - id: fastfall_boots_gold
            name: Midas
            material: minecraft:golden_boots
            description: "\"Everything I touch turns to gold...\""
            cost: 15000
          - id: fastfall_boots_tnt
            name: TNT
            item:
              material: minecraft:leather_boots
              dye: 255, 0, 0
            description: "Explode the competition when you die! (Decorative)"
            cost: 15000
  - name: WackyMaze
    material: minecraft:stick
    groups:
      - name: Knockback Stick
        material: minecraft:stick
        description: |
          Fancy upgrades for the standard
          knockback stick.
        cosmetics:
          - id: wackymaze_stick_fish
            name: Fish
            material: minecraft:cod
            description: "A fish? Really?"
            cost: 5000
          - id: wackymaze_stick_door
            name: Oak Door
            material: minecraft:oak_door
            description: "Doesn't seem very aerodynamic..."
            cost: 5000
          - id: wackymaze_stick_bamboo
            name: Bamboo
            material: minecraft:bamboo
            description: "Environmentally friendly!"
            cost: 5000
          - id: wackymaze_stick_hoe
            name: Netherite Hoe
            material: minecraft:netherite_hoe
            description: "Overkill."
            cost: 5000
          - id: wackymaze_stick_deadbush
            name: Dead Bush
            material: minecraft:dead_bush
            description: "Hopefully not as dead as you are."
            cost: 5000
  - name: Global
    material: minecraft:diamond_block
    groups:
      - name: Firework Color
        material: minecraft:firework_rocket
        description: |
          The color of fireworks set off
          when you win a game on BlueDragon.
        cosmetics:
          - id: global_firework_red
            name: Red
            material: minecraft:red_wool
            description: "Red fireworks as a win effect."
            cost: 500
          - id: global_firework_orange
            name: Orange
            material: minecraft:orange_wool
            description: "Orange fireworks as a win effect."
            cost: 500
          - id: global_firework_yellow
            name: Yellow
            material: minecraft:yellow_wool
            description: "Yellow fireworks as a win effect."
            cost: 500
          - id: global_firework_green
            name: Green
            material: minecraft:green_wool
            description: "Green fireworks as a win effect."
            cost: 500
          - id: global_firework_blue
            name: Blue
            material: minecraft:blue_wool
            description: "Blue fireworks as a win effect."
            cost: 500
          - id: global_firework_purple
            name: Purple
            material: minecraft:purple_wool
            description: "Purple fireworks as a win effect."
            cost: 500
          - id: global_firework_rainbow
            name: Rainbow
            material: minecraft:emerald_block
            description: "Rainbow fireworks as a win effect."
            cost: 2000
  - name: Lobby
    material: minecraft:dragon_head
    groups:
      - name: Double Jump Effect
        material: minecraft:iron_boots
        description: |
          Sweet particles and other effects
          that show up when you double jump
          in the Lobby.
        cosmetics:
          - id: lobby_double_jump_note
            name: Note
            material: minecraft:note_block
            description: |
              A musical effect which appears 
              all around you when you double jump.
            cost: 1500
          - id: lobby_double_jump_cloud
            name: Cloud
            material: minecraft:white_wool
            description: |
              A cloud effect which appears 
              all around you when you double jump.
            cost: 1500
      - name: Hat
        material: minecraft:player_head
        description: |
          Protect your head and look
          stylish at the same time.
        cosmetics:
          - id: lobby_hat_glass
            name: Space Helmet
            material: minecraft:glass
            description: |
              Liftoff!
            cost: 500
          - id: lobby_hat_ice
            name: Ice
            material: minecraft:ice
            description: |
              This doesn't look very comfortable.
            cost: 500
          - id: lobby_hat_slime
            name: Slime
            material: minecraft:slime_block
            description: |
              Someone get this off me!
            cost: 500
          - id: lobby_hat_honey
            name: Honey
            material: minecraft:honey_block
            description: |
              Sweet and tasty.
            cost: 500
          - id: lobby_hat_jack_o_lantern
            name: Jack-o-Lantern
            material: minecraft:jack_o_lantern
            description: |
              Spooky!
            cost: 500
          - id: lobby_hat_compass
            name: Compass
            material: minecraft:compass
            description: |
              Always know where you're going.
            cost: 500
          - id: lobby_hat_clock
            name: Clock
            material: minecraft:clock
            description: |
              Always know what time it is.
            cost: 500
          - id: lobby_hat_netherite_helmet
            name: Helmet
            material: minecraft:netherite_helmet
            description: |
              The ultimate protection.
            cost: 500
          - id: lobby_hat_creeper_head
            name: Creeper Head
            material: minecraft:creeper_head
            description: |
              Shh.
            cost: 500
          - id: lobby_hat_zombie_head
            name: Zombie Head
            material: minecraft:zombie_head
            description: |
              Braaains.
            cost: 500
          - id: lobby_hat_steve_head
            name: Steve Head
            material: minecraft:player_head
            description: |
              A fresh new look.
            cost: 500
          - id: lobby_hat_skeleton_skull
            name: Skeleton Skull
            material: minecraft:skeleton_skull
            description: |
              Bow not included.
            cost: 500
          - id: lobby_hat_wither_skeleton_skull
            name: Wither Skeleton Skull
            material: minecraft:wither_skeleton_skull
            description: |
              Defender of the fortress.
            cost: 500
          - id: lobby_hat_dragon_head
            name: Dragon Head
            material: minecraft:dragon_head
            description: |
              Terrify the other players in the lobby.
            cost: 5000