npcs:
  - name: "<bold><a1>WackyMaze"
    pos: 0.5, 62.5, -35.5 # CENTER
    look-at: 0.5, 64.25, -31.5
    game: WackyMaze
    skin:
      textures: "ewogICJ0aW1lc3RhbXAiIDogMTU4ODczNDk5Nzk5MCwKICAicHJvZmlsZUlkIiA6ICJhMDA0ODE0MzQ2MGY0MTdlOTExOWYzMGViOTY3NGE3YSIsCiAgInByb2ZpbGVOYW1lIiA6ICJza2F0ZXI3N2kiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjhkNmRiMzQwM2VlNTYyYTY3ODAxYTNkODczNWRhN2YwYTAyOGMwZDVmZmUyNzc3OGZmODMzYWU5YjM5NjY3MSIKICAgIH0KICB9Cn0="
      signature: "VmLuwGvhhNk9EIfbrvOek2GIJH0kbUn3wQgmPdw9B7tdWKB4eQFioSUPWX2GAcaqVUphVY9RBmQosx1DaA10NpnzZWgRpcSmBz2//oKDuxzonmucYx8zr/0/7Jw2nZxhcGB4+K4d1bQRMCx+PslEZJ2z+hQHoXG+cis4QAFzackqqi1rkNoB6wK/txf0iFusQOYKIPtigpiBlNmz13u+WtqDA1L7e5e1SkcywQYKyPOQgPfVEfolLCC+6T0wwhzHOIvNSSKbUPuMd0ntJbb5t3XrcwZ9nsc1oJjvMeQGu1xP4QNiKwJX3HIzh0R8rNZh+I3VmG4E0G6RGFge7Dq2KGkW4TevCTa5f5Gs5j5Av3R6Bz46JHguqfj2joezNVSTTudW9eLxC3ACatQNcKgOtIgQh2n/wzGDeHE1ioD6hfYT2CE50c64DE9/hN6oKh8XkCZarG39LeBq+QL8fz7KAfSrNeGw1l8q6YKWtDu247vVal1U2EIv//NmAkO14Q1n/lRO3aLCqhb5dU0n7+f9GXaNrbwHC/kT7mXbjGp8uWD+hb5UHgXvLVHCXF68YUA6yqz2InD+nn3Dv8laJZ6c09wR+mx5Xc/rGSppRzahQdX7WnbHlzgguRJVhFCpsxPbWQnw6G5M84IR4ACkPjSaijom0wLUZJIUBP+uTPAEeoc="
  - name: "<bold><a1>BedWars"
    pos: -3.5, 62.5, -34.5 # LEFT OF CENTER
    look-at: 0.5, 64.25, -31.5
    game: BedWars
    skin:
      textures: "ewogICJ0aW1lc3RhbXAiIDogMTY1NjUxMTY2MTA3NCwKICAicHJvZmlsZUlkIiA6ICI4YWFlYTdlYjViOWM0ZWEwODUxNWU3MDhhZGIxODBkNyIsCiAgInByb2ZpbGVOYW1lIiA6ICJNYVBhODA3MTEiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmUxOWI0MGMyZTYxZGJhNDI4N2ZlZmFiMmRkZTAxNDVhZWUzYjQwOTZmYzAzZjNjYzg0YTM4NTllYmRlNjJkZiIKICAgIH0KICB9Cn0="
      signature: "GGRW7hVdqxJ4yrqkmYTq6XjL6IAoVs/rDyPXkO5M/BnBCcN5wI6TjlCpKfr7Jv2tFPFQYUTou29ERTk8mviAGhXBZAs2bmOHlZpWS2st2cKw6c3Dhb9qV0/xB8BG+rdnfdCdzcGw6V+gOE1as89RFq6xXd5pcI14pj/CYmS7h1OAu38s28iOHqd2MRPGW2EGXbOzZAGBCeHhnipL4GJCGjIEVutIZFkhz2nlbL8Qe7vIEC6c9Giv+7z7agKdQ4KIzc1Q9pDnht9jXlZ8pSGrPQthviBud+1JWvyyOmDh9GctifWkw2mXU91cQ/PlrNUW8rcKI+fVDNhxm/wI5rx/YByOLV1kJ1K4VlB/sKUM7wTDrvd4ayXhvFCAB9i1kRisue5kqaA+FSc/n5f8WoxZYPwunFDeIFD99mJxQeS512WbufWeTDbxmfcXkFwn9bLUYnJ38pGNZFOxh76NWASLI5eMoN9hceO9K38rLtF0Amnh6Nd5DAB2Raylbg3X2+vxRrbeX9S9yZPdq8kE+7KcFZUF6pkNbpa5IM/tbWkJkkiGZUT0QT6pXY3wljm9qgPc/8QfzfuLH7thqxBcsWoKalcgLaQFjPu36ZsmSXhE5TBQTUd4rbZPEcsPXv4JcFGwl/bmq9OykCubr18rqanbOdhwmZspgIALwclDSnBNN6U="
  - name: "<bold><a1>SkyWars"
    pos: 4.5, 62.5, -34.5 # RIGHT OF CENTER
    look-at: 0.5, 64.25, -31.5
    game: SkyWars
    skin:
      textures: "ewogICJ0aW1lc3RhbXAiIDogMTU5MTk3NzgyMjU0NCwKICAicHJvZmlsZUlkIiA6ICI1NjY3NWIyMjMyZjA0ZWUwODkxNzllOWM5MjA2Y2ZlOCIsCiAgInByb2ZpbGVOYW1lIiA6ICJUaGVJbmRyYSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jODA3NTdkYzk5YWMzZTBhMTRiMThkYjFhMmE1MTA1MGQ0NmMwMjFjMmQ2OGI4NTQ1ZDY0ZTNjNTMwNTExMjZjIgogICAgfQogIH0KfQ=="
      signature: "wZpdk+lBga7MTiITrCMYfdTXLUWrNpWJ1IrXYEjEsL2aZM8q21AbBNGVmEUqobHp+Z6lNxHc6pwPn/u7qNmlRhV130cq5Arm+tQQePRYZmzGt7SyP2/NImWdYbhTTLo6hjAK1Ifj11pFHzJXLjatufSelQWtmK5si3WTkphRV8iH1GdH0aksas6xPERqJ6lhi4aWKPHEHpNuK/6etRcTDW6pJmTbOcCRZCi7N/DlAbdmT1Klvbxm5fyDaBO/1uIv1TNe0SMYH6v38GAg+gfow6BBDCBsqATzdk0dYAxP4xxLFRcBxqgSz/yK1ZqOc2lFllutxZXjf3ucqR/Gh9iNB31zXtuwX3bdZVMeMLuNUqGiDUtQYRM37twMqLdk07jfkJBMpj3MIgTWa8jGWJgS4kMcGT134eMAfBvw0Q17TqfVdzcc+lCGsVYK5VNcx8wn/BXIGZsqITG4Jsk7kpqxE39he9iRAWNH4myylhdyrbS+USkGzYI5J1lZcGfGllGogwZplfWt7bQSfedgSDTBbWblVM5OJMo0TAQK2tqukhunrSk+w+lW8TXnylpcqTL8BIxtTerSjyxPHtaclzK8kXweONzAM84/uuA7WELgMzk4fNysT0pGZthp2O4UPPCCdwka6z9JoLT26Klx4yEik5tn4oc9oz3kQwx+UZzBIK8="
  - name: "<bold><a1>FastFall"
    pos: -5.5, 62.5, -32.5 # LEFT OF LEFT OF CENTER
    look-at: 0.5, 64.25, -31.5
    game: FastFall
    skin:
      textures: "ewogICJ0aW1lc3RhbXAiIDogMTYwMDU4ODE2NDEwMiwKICAicHJvZmlsZUlkIiA6ICJhYTZhNDA5NjU4YTk0MDIwYmU3OGQwN2JkMzVlNTg5MyIsCiAgInByb2ZpbGVOYW1lIiA6ICJiejE0IiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzIzODMxMjhkYzc0ODM2OGJkYWVmZjkyNDEyMDg3ODNlNmQ2ZmQ5YmJjZmMxYjk3OWVlZDNjMTZiY2RlOTI1ODkiCiAgICB9CiAgfQp9"
      signature: "FgbH2ikvfoDBi/VKqsVx0pLA6OnB/lrGVZG8qfeuNfmE8Ln/HQ8z+rU+8kYpoXJuIsoJlEOCSxCVWMy1dorHnYflMYyKZ6EYflVhOAwJkXpHlC71zN82/DhEKuH0V4LeRYw8ehODe2DAH5+kYbjCFoCd+vuNJvwQqhvpiMG1PUKzIEnDtwDMsptjPCZSo4mUa+bBjHv98mEL4XUmOq4IDRQRtzsN6HYgrx7AcJwkwStufXQ3hrU0yqGYSU83lSUx0P6YFQ6Cp0WSrda6NF475z93Cpxbt8GRSbP+d6qu1gdSm5K6F2Y3/BJQsR8r1pRLcEXlzMJyhwi3ckwC8Oi6chOOkYbHv8/tISdZ7jcMax9jaPSOnw9F1ohRZp8gyKKjhRQy2T6KNJSLffgotZ5DKH1ByhHFmyBnz6XwQZlMTCTtUQT5ExUuJ1L0ca/Q/AWYOPZybXHU+RDav05URXGHoBcDvsZShuHXEmmLuPvNKA8wNLcJvMpee1a3n35EY1QcGBcsRqRsvhq2C2LfHNg0xcWTnmZ/03v1hyTmq418VnwH0xZlFi0/bK7/sJ+9jebaUj6ipqwTHj7gS6gOgZYIQQPVcs5y5KXtR1bjl4LBgviiu9AlGWVmMMLT9pYs6OOqhPiGe4rfQ6LGrdMdVngk3f8CqPDovC/qG154P3J0XxE="
  - name: "<bold><a1>Infection"
    pos: 6.5, 62.5, -32.5 # RIGHT OF RIGHT OF CENTER
    look-at: 0.5, 64.25, -31.5
    game: Infection
    entity-type: "minecraft:zombie"
  - name: "<bold><a1>Infinijump"
    pos: -7.5, 62.5, -30.5 # FAR LEFT
    look-at: 0.5, 64.25, -31.5
    game: Infinijump
    skin:
      textures: "ewogICJ0aW1lc3RhbXAiIDogMTY1OTA1NTU5NjU1MCwKICAicHJvZmlsZUlkIiA6ICI3MzY0ODFkZmY2ZGY0NWUwOTA0ODg0ZjNiMWExMjY1NSIsCiAgInByb2ZpbGVOYW1lIiA6ICJUd2lsaWdodFFBUSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9lMjQ3MmU1MTNiYmMzZTQ3YWFkZTJlMTZlODg5MzZhZWE1MzY5N2M3MjJlZmJiNjBlNDdjZmQ3MjVjMWE4YTM0IgogICAgfQogIH0KfQ=="
      signature: "PHZYWoFj/uEkJDVbzEIr3vFMi5RVW4JJNyvtRfjDbwNa6RmX+j2BadYRIh7nruXBtjcQBTaT13ooI5VzKX+DfXjMkXuwtjvPLRZaHlyUa/smpeWTt6sbJavhwhLHa7+1Lqo664YfbFTmxH3p3XEscGV83XACShoGX8gqpECDLU/RgTas4gZh8aQ0pLYmQeEnf2ZoW1Ky/nTkpcpgguq5QMm4RoUyGAQdCR7EP8EUEZ6NIrjK9aareEEBukswHPmVLAwR4gL1vskU7Tl1ixsIOZisCOjb1FCc2108tz8md/xuafbDbb0jKZbDQz6FtnuYszLQN9OrJgBch7SqfDtZT6SSSAhTLVtAGaK6dHg4F+qGSSlpt1mqDmZVrxO+dwLjkfLutofhQYxng1GSU4r9d55Jge8mpBNqAC0UW/agTSmzs7lVNPcmbj1djDiwPxQ25B2eVvvo1tTqJq/q25HpF7PJoyj3WCWx5dYgiDH0C+jKy3g3nsFsuPMm7yTdvSw8PGYoM+1WFcL00WRfGdve42laTZ0saP461JpwefZOP9E6woqmLuqtb8xKt1p8P2M1qHfiABIinP2fT4ECPFOtcbJvcevb5EIhPEmQxgmemygnfg+2AQviAk8ZD8YhFxzQ3mH3JAEoaSQ4qsNJ2HHXLwGXgfL79WlN/iR72Sm1S1w="
  - name: "<bold><a1>ArenaPvP"
    pos: 8.5, 62.5, -30.5 # FAR RIGHT
    look-at: 0.5, 64.25, -31.5
    game: ArenaPvP
    skin:
      textures: "ewogICJ0aW1lc3RhbXAiIDogMTY2MDUxNTk1ODA4MiwKICAicHJvZmlsZUlkIiA6ICIzYWJkYjI5ZDI2MTU0YTAxOWEzZWQ3OGRlMzI4OWUxNCIsCiAgInByb2ZpbGVOYW1lIiA6ICJFcmljSHViZXIiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmUyZDc4MmM5ZWQ4Yzc5ZGIzZWYxNTU0MDc3YWI5OGZlM2ZkMjNkYWI1NjllZDM2MzgwNTkxYWE2OTgxY2I1YSIKICAgIH0KICB9Cn0="
      signature: "adcENH0HEN3Le9gFy2Mvoeu+Hln1kDZSGF5fvJ8q+I1FluRH18GgjhYr/WGmHlIZ6JvSkb4+TN8p02au+i6KlOhXUkzVGWAWYeD0sr1IxtX+0T1vRgjRT1ybRA3M/fjkDRXLhiZwDGtgP5Uo5y0k1X71GOhetDWRCdLw8Hty0jU6L4h2Lf19N1oRaEgTRNFBsZaPGAwWCiItjEfSMu/voaOkmnIUPRLOHLRccMM+XZBClrcemVzWHlh9x9m2CLZWpngFBqEwZrmzM3/J4MtHP/vD7FDBGFV6waKft3pwBcHCYR1sKB9EMbjlafOtcoFeo1+07HDzLOEygqv2cvfGlBWmwvb4b/7iO7AcswNVVn9IaUUF7kYEEFjjP5Aznv8/8PCTLGTruHp7xk3BL2xAHbGaJ0XpvpO7RnB1WfFxNcOxE71Er35m7m4hj8m4n02r5+vZ6xJuVhnD0SeCQyrE7jSnXg/KyksV1e4HIVM1VGuZbCNsRMhuHfnU0zmpsYISh/cZlW4CRmBtPWowHQzLGXpP7SmnD4cvs3FUjx2m7G9U7K+3SxuL3vfxxI6XX4IBiA/TjX6bbJfogDvKurR6hwfSxuDnMeoGhbjrGW6Xg1NNi1WC469b6AB999HzjR3Q9RGUSSbsb34n09WQ21XdtPBUiktfsGccbismhKUKe80="
  - name: "<bold><a1><lang:lobby.npc.lb_browser>"
    pos: 49.5, 61.0, -28.5, 45.0, 0.0 # Leaderboard island area
    look-at: 47.5, 62.5, -27.5 # Looking at the pathway
    menu: leaderboard_browser
    skin:
      textures: "ewogICJ0aW1lc3RhbXAiIDogMTY2MDUxNTk1ODA4MiwKICAicHJvZmlsZUlkIiA6ICIzYWJkYjI5ZDI2MTU0YTAxOWEzZWQ3OGRlMzI4OWUxNCIsCiAgInByb2ZpbGVOYW1lIiA6ICJFcmljSHViZXIiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmUyZDc4MmM5ZWQ4Yzc5ZGIzZWYxNTU0MDc3YWI5OGZlM2ZkMjNkYWI1NjllZDM2MzgwNTkxYWE2OTgxY2I1YSIKICAgIH0KICB9Cn0="
      signature: "adcENH0HEN3Le9gFy2Mvoeu+Hln1kDZSGF5fvJ8q+I1FluRH18GgjhYr/WGmHlIZ6JvSkb4+TN8p02au+i6KlOhXUkzVGWAWYeD0sr1IxtX+0T1vRgjRT1ybRA3M/fjkDRXLhiZwDGtgP5Uo5y0k1X71GOhetDWRCdLw8Hty0jU6L4h2Lf19N1oRaEgTRNFBsZaPGAwWCiItjEfSMu/voaOkmnIUPRLOHLRccMM+XZBClrcemVzWHlh9x9m2CLZWpngFBqEwZrmzM3/J4MtHP/vD7FDBGFV6waKft3pwBcHCYR1sKB9EMbjlafOtcoFeo1+07HDzLOEygqv2cvfGlBWmwvb4b/7iO7AcswNVVn9IaUUF7kYEEFjjP5Aznv8/8PCTLGTruHp7xk3BL2xAHbGaJ0XpvpO7RnB1WfFxNcOxE71Er35m7m4hj8m4n02r5+vZ6xJuVhnD0SeCQyrE7jSnXg/KyksV1e4HIVM1VGuZbCNsRMhuHfnU0zmpsYISh/cZlW4CRmBtPWowHQzLGXpP7SmnD4cvs3FUjx2m7G9U7K+3SxuL3vfxxI6XX4IBiA/TjX6bbJfogDvKurR6hwfSxuDnMeoGhbjrGW6Xg1NNi1WC469b6AB999HzjR3Q9RGUSSbsb34n09WQ21XdtPBUiktfsGccbismhKUKe80="
tips:
  - "<p2><click:open_url:'https://bluedragonmc.com'><lang:lobby.tips.forum></click>"
  - "<p2><click:open_url:'https://discord.gg/3gvSPdW'><lang:lobby.tips.discord></click>"
  - "<p2><lang:lobby.tips.newest_game:'<p1>Infinijump'>"
  - "<p2><lang:lobby.tips.extra.1>"
  - "<p2><lang:lobby.tips.extra.2>"
  - "<p2><lang:lobby.tips.extra.3>"
splashes:
  - Welcome back!
  - Try Infinijump!
  - Enjoy your stay!
  - Professional software!
  - Have you seen Joe?
games:
  - game: WackyMaze
    category: Combat
    time: 1min
    description: <lang:game.wackymaze.motd>
    material: minecraft:stick
  - game: PvPMaster
    category: Combat
    time: 5min
    description: <lang:game.pvpmaster.motd>
    material: minecraft:netherite_sword
  - game: ArenaPvP
    category: Combat
    time: "\u221e" # Infinite
    description: <lang:game.arenapvp.motd>
    material: minecraft:iron_chestplate
  - game: FastFall
    category: Parkour
    time: 5min
    description: <lang:game.fastfall.motd>
    material: minecraft:iron_boots
  - game: Infection
    category: Hide and Seek
    time: 3min
    description: <lang:game.infection.motd>
    material: minecraft:rotten_flesh
  - game: SkyWars
    category: Combat
    time: 3min
    description: <lang:game.skywars.motd>
    material: minecraft:iron_sword
  - game: BedWars
    category: Combat
    time: 15min
    description: <lang:game.bedwars.motd>
    material: minecraft:red_bed
  - game: Infinijump
    category: Parkour
    time: "\u221e" # Infinite
    description: <lang:game.infinijump.motd>
    material: minecraft:feather
leaderboards:
  - title: FastFall # LEFT
    subtitle: Fastest time
    statistic: game_fastfall_best_time
    display-mode: DURATION
    order-by: ASC
    top-left: 52.0,64.0,-29.0
    bottom-right: 52.0,61.0,-26.0
    orientation: WEST
  - title: WackyMaze # MIDDLE
    subtitle: Most wins
    statistic: game_wackymaze_wins
    display-mode: WHOLE_NUMBER # one of: WHOLE_NUMBER, DECIMAL, or DURATION
    top-left: 52.0,64.0,-24.0
    bottom-right: 52.0,61.0,-21.0
    orientation: WEST
  - title: Infinijump # RIGHT
    subtitle: Highest score
    statistic: game_infinijump_highest_score
    display-mode: WHOLE_NUMBER
    top-left: 52.0,64.0,-19.0
    bottom-right: 52.0,61.0,-16.0
    orientation: WEST
leaderboard-browser:
  - name: WackyMaze
    icon: minecraft:stick
    leaderboards:
      - title: Most Wins
        icon: minecraft:gold_block
        statistic: game_wackymaze_wins
        display-mode: WHOLE_NUMBER
  - name: PvPMaster
    icon: minecraft:netherite_sword
    leaderboards:
      - title: Most Wins
        icon: minecraft:gold_block
        statistic: game_pvpmaster_wins
        display-mode: WHOLE_NUMBER
  - name: FastFall
    icon: minecraft:iron_boots
    leaderboards:
      - title: Most Wins
        subtitle: Singleplayer mode not included.
        icon: minecraft:gold_block
        statistic: game_fastfall_wins
        display-mode: WHOLE_NUMBER
      - title: Fastest Time
        icon: minecraft:feather
        statistic: game_fastfall_best_time
        display-mode: DURATION
        order-by: ASC
  - name: Infection
    icon: minecraft:rotten_flesh
    leaderboards:
      - title: Most Wins
        icon: minecraft:gold_block
        statistic: game_infection_wins
        display-mode: WHOLE_NUMBER
  - name: SkyWars
    icon: minecraft:iron_sword
    leaderboards:
      - title: Most Wins
        icon: minecraft:gold_block
        statistic: game_skywars_wins
        display-mode: WHOLE_NUMBER
  - name: BedWars
    icon: minecraft:red_bed
    leaderboards:
      - title: Most Wins
        icon: minecraft:gold_block
        statistic: game_bedwars_wins
        display-mode: WHOLE_NUMBER
  - name: Infinijump
    icon: minecraft:feather
    leaderboards:
      - title: Highest Score
        icon: minecraft:gold_block
        statistic: game_infinijump_highest_score
        display-mode: WHOLE_NUMBER