loot:
  spawn:
  - material: minecraft:white_wool
    chance: 1.0
    quantity: 12-36
  - material: minecraft:cooked_beef
    chance: 0.5
    quantity: 1-3
  - material: minecraft:stone_sword
    chance: 0.5
    quantity: 1
  - material: minecraft:iron_sword
    chance: 0.5
    quantity: 1
  - material: minecraft:leather_helmet
    chance: 0.15
    quantity: 1
  - material: minecraft:leather_chestplate
    chance: 0.15
    quantity: 1
  - material: minecraft:leather_leggings
    chance: 0.15
    quantity: 1
  - material: minecraft:leather_boots
    chance: 0.15
    quantity: 1
  - material: minecraft:chainmail_helmet
    chance: 0.10
    quantity: 1
  - material: minecraft:chainmail_chestplate
    chance: 0.10
    quantity: 1
  - material: minecraft:chainmail_leggings
    chance: 0.10
    quantity: 1
  - material: minecraft:chainmail_boots
    chance: 0.10
    quantity: 1
  - material: minecraft:iron_helmet
    chance: 0.05
    quantity: 1
  - material: minecraft:iron_chestplate
    chance: 0.05
    quantity: 1
  - material: minecraft:iron_leggings
    chance: 0.05
    quantity: 1
  - material: minecraft:iron_boots
    chance: 0.05
    quantity: 1
  middle:
  - material: minecraft:white_wool
    chance: 1.0
    quantity: 8-16
  - material: minecraft:golden_apple
    chance: 1.0
    quantity: 0-3
  - material: minecraft:iron_sword
    chance: 0.5
    quantity: 1
  - material: minecraft:diamond_sword
    chance: 0.5
    quantity: 1
  - material: minecraft:flint_and_steel
    chance: 0.4
    quantity: 1
  - material: minecraft:iron_helmet
    chance: 0.20
    quantity: 1
  - material: minecraft:iron_chestplate
    chance: 0.20
    quantity: 1
  - material: minecraft:iron_leggings
    chance: 0.20
    quantity: 1
  - material: minecraft:iron_boots
    chance: 0.20
    quantity: 1
  - material: minecraft:diamond_helmet
    chance: 0.125
    quantity: 1
  - material: minecraft:diamond_chestplate
    chance: 0.125
    quantity: 1
  - material: minecraft:diamond_leggings
    chance: 0.125
    quantity: 1
  - material: minecraft:diamond_boots
    chance: 0.125
    quantity: 1
  - material: minecraft:netherite_helmet
    chance: 0.01
    quantity: 1
  - material: minecraft:netherite_chestplate
    chance: 0.01
    quantity: 1
  - material: minecraft:netherite_leggings
    chance: 0.01
    quantity: 1
  - material: minecraft:netherite_boots
    chance: 0.01
    quantity: 1
  - item:
      material: minecraft:stick
      enchants:
       minecraft:knockback: 2
      name: Knockback Stick
      lore:
        - <gray>Use this to wack your enemies
        - <gray>off the map!
    chance: 0.16
    quantity: 1