levels:
  - name: <black>Nothing
    description: <a1>Nothing at all!
  - name: <#5f3c26>Leather
    description: <a1>One kill to go!
    items:
      helmet:
        material: minecraft:leather_helmet
      chestplate:
        material: minecraft:leather_chestplate
      leggings:
        material: minecraft:leather_leggings
      boots:
        material: minecraft:leather_boots
      0:
        material: minecraft:wooden_sword
  - name: <a2>Gold
    description: <a1>Like having no armor at all!
    items:
      helmet:
        material: minecraft:golden_helmet
      chestplate:
        material: minecraft:golden_chestplate
      leggings:
        material: minecraft:golden_leggings
      boots:
        material: minecraft:golden_boots
      0:
        material: minecraft:golden_sword
  - name: <dark_gray>Chainmail
    description: <a1>Still better than gold.
    items:
      helmet:
        material: minecraft:chainmail_helmet
      chestplate:
        material: minecraft:chainmail_chestplate
      leggings:
        material: minecraft:chainmail_leggings
      boots:
        material: minecraft:chainmail_boots
      0:
        material: minecraft:stone_sword
  - name: <white>Iron
    description: <a1>Shiny!
    items:
      helmet:
        material: minecraft:iron_helmet
      chestplate:
        material: minecraft:iron_chestplate
      leggings:
        material: minecraft:iron_leggings
      boots:
        material: minecraft:iron_boots
      0:
        material: minecraft:iron_sword
  - name: <aqua>Diamond
    description: <a1>Rock solid!
    items:
      helmet:
        material: minecraft:diamond_helmet
      chestplate:
        material: minecraft:diamond_chestplate
      leggings:
        material: minecraft:diamond_leggings
      boots:
        material: minecraft:diamond_boots
      0:
        material: minecraft:diamond_sword
  - name: <#383538>Netherite
    description: <a1>Get 6 kills to win!
    items:
      helmet:
        material: minecraft:netherite_helmet
      chestplate:
        material: minecraft:netherite_chestplate
      leggings:
        material: minecraft:netherite_leggings
      boots:
        material: minecraft:netherite_boots
      0:
        material: minecraft:netherite_sword