block-sets:
  classic:
    - minecraft:red_bed
    - minecraft:oak_pressure_plate
    - minecraft:oak_planks
    - minecraft:stone
    - minecraft:diamond_block
    - minecraft:sea_lantern
    - minecraft:glowstone
    - minecraft:dirt
    - minecraft:oak_log
    - minecraft:iron_trapdoor
    - minecraft:nether_portal
    - minecraft:pumpkin
    - minecraft:white_stained_glass
    - minecraft:beacon
    - minecraft:obsidian
    - minecraft:sandstone
    - minecraft:hay_block
    - minecraft:chest
    - minecraft:piston
    - minecraft:melon
    - minecraft:andesite
    - minecraft:stone_slab
  nether:
    - minecraft:blackstone
    - minecraft:gilded_blackstone
    - minecraft:soul_soil
    - minecraft:soul_sand
    - minecraft:magma_block
    - minecraft:warped_nylium
    - minecraft:crimson_nylium
    - minecraft:nether_bricks
    - minecraft:nether_brick_fence
    - minecraft:red_nether_bricks
    - minecraft:obsidian
    - minecraft:crying_obsidian
    - minecraft:netherrack
    - minecraft:warped_planks
    - minecraft:crimson_planks
    - minecraft:nether_wart_block
    - minecraft:netherite_block
    - minecraft:nether_gold_ore
    - minecraft:nether_quartz_ore
    - minecraft:deepslate
    - minecraft:cobbled_deepslate
    - minecraft:polished_deepslate
  colors:
    - minecraft:white_concrete
    - minecraft:orange_concrete
    - minecraft:magenta_concrete
    - minecraft:light_blue_concrete
    - minecraft:yellow_concrete
    - minecraft:lime_concrete
    - minecraft:pink_concrete
    - minecraft:gray_concrete
    - minecraft:light_gray_concrete
    - minecraft:cyan_concrete
    - minecraft:purple_concrete
    - minecraft:blue_concrete
    - minecraft:brown_concrete
    - minecraft:green_concrete
    - minecraft:red_concrete
    - minecraft:black_concrete
    - minecraft:white_wool
    - minecraft:orange_wool
    - minecraft:magenta_wool
    - minecraft:light_blue_wool
    - minecraft:yellow_wool
    - minecraft:lime_wool
    - minecraft:pink_wool
    - minecraft:gray_wool
    - minecraft:light_gray_wool
    - minecraft:cyan_wool
    - minecraft:blue_wool
    - minecraft:brown_wool
    - minecraft:green_wool
    - minecraft:red_wool
    - minecraft:black_wool
    - minecraft:white_stained_glass
    - minecraft:orange_stained_glass
    - minecraft:magenta_stained_glass
    - minecraft:light_blue_stained_glass
    - minecraft:yellow_stained_glass
    - minecraft:lime_stained_glass
    - minecraft:pink_stained_glass
    - minecraft:gray_stained_glass
    - minecraft:light_gray_stained_glass
    - minecraft:cyan_stained_glass
    - minecraft:blue_stained_glass
    - minecraft:brown_stained_glass
    - minecraft:green_stained_glass
    - minecraft:red_stained_glass
    - minecraft:black_stained_glass
  forest:
    - minecraft:oak_log
    - minecraft:spruce_log
    - minecraft:birch_log
    - minecraft:jungle_log
    - minecraft:acacia_log
    - minecraft:dark_oak_log
    - minecraft:oak_leaves
    - minecraft:spruce_leaves
    - minecraft:birch_leaves
    - minecraft:jungle_leaves
    - minecraft:acacia_leaves
    - minecraft:dark_oak_leaves
  ocean:
    - minecraft:tube_coral_block
    - minecraft:brain_coral_block
    - minecraft:bubble_coral_block
    - minecraft:fire_coral_block
    - minecraft:horn_coral_block
    - minecraft:horn_coral_block
    - minecraft:prismarine
    - minecraft:prismarine_bricks
    - minecraft:dark_prismarine
    - minecraft:sand
    - minecraft:clay
    - minecraft:gravel
    - minecraft:dirt
    - minecraft:stone
    - minecraft:water
    - minecraft:sponge